name: bio 
version: 0.0.0
homepage: https://github.com/morloclib/bio
synopsis: Core functions and types for computational biology
description: Bioinformatics data structures and algorithms
category: science
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloclib/bio
bug-reports: https://github.com/morloclib/bio
