name: fasta
version: 0.0.0
homepage: null
synopsis: FASTA sequence handling
description: Basic support for reading, writing, and linting FASTA files
category: bioinformatics, file handling
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: null
bug-reports: null
